### ISSUE TITLE
App Crashes when screen is locked

### ISSUE THREAD

**Issue by rs1257** [bp713/GPIG-Team-A#2]
The app crashes when the screen is locked. The message below seems to suggest that there is an issue when calling onStop method for the activity. This might be related to the change where onStop starts the login screen again. Maybe I need to modify this code.

Process: com.gpig.a, PID: 13636
    java.lang.RuntimeException: Unable to stop activity {com.gpig.a/com.gpig.a.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.content.Intent.migrateExtraStreamToClipData()' on a null object reference
        at android.app.ActivityThread.callActivityOnStop(ActivityThread.java:4720)
        at android.app.ActivityThread.handleSleeping(ActivityThread.java:4852)
        at android.app.ActivityThread.access$3100(ActivityThread.java:267)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2062)
        at android.os.Handler.dispatchMessage(Handler.java:109)
        at android.os.Looper.loop(Looper.java:207)
        at android.app.ActivityThread.main(ActivityThread.java:7470)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:958)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.content.Intent.migrateExtraStreamToClipData()' on a null object reference
        at android.app.Instrumentation.execStartActivity(Instrumentation.java:1743)
        at android.app.Activity.startActivityForResult(Activity.java:4781)
        at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:767)
        at android.app.Activity.startActivityForResult(Activity.java:4721)
        at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:754)
        at android.app.Activity.startActivity(Activity.java:5142)
        at android.app.Activity.startActivity(Activity.java:5110)
        at com.gpig.a.MainActivity.onStop(MainActivity.java:140)
        at android.app.Instrumentation.callActivityOnStop(Instrumentation.java:1490)
        at android.app.Activity.performStop(Activity.java:7686)
        at android.app.ActivityThread.callActivityOnStop(ActivityThread.java:4712)
        at android.app.ActivityThread.handleSleeping(ActivityThread.java:4852) 
        at android.app.ActivityThread.access$3100(ActivityThread.java:267) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2062) 
        at android.os.Handler.dispatchMessage(Handler.java:109) 
        at android.os.Looper.loop(Looper.java:207) 
        at android.app.ActivityThread.main(ActivityThread.java:7470) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:958)

**Comment by rs1257** [comment]
Needed to remove the location listener onStop in the fragment
