### ISSUE TITLE
RouteCourierTask causing crash

### ISSUE THREAD

**Issue by TomG736** [bp713/GPIG-Team-A#30]
When i opened the app and went straight to 'check in' -> 'Verify' it crashed with the following:

```
2019-05-28 18:01:10.361 29900-29900/com.gpig.a E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.gpig.a, PID: 29900
    java.lang.NullPointerException: Attempt to invoke virtual method 'void android.support.v7.widget.RecyclerView.setLayoutManager(android.support.v7.widget.RecyclerView$LayoutManager)' on a null object reference
        at com.gpig.a.MapFragment$4.processFinish(MapFragment.java:167)
        at com.gpig.a.MapFragment$RouteCourierTask.onPostExecute(MapFragment.java:362)
        at com.gpig.a.MapFragment$RouteCourierTask.onPostExecute(MapFragment.java:341)
        at android.os.AsyncTask.finish(AsyncTask.java:727)
        at android.os.AsyncTask.access$600(AsyncTask.java:180)
        at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:744)
        at android.os.Handler.dispatchMessage(Handler.java:109)
        at android.os.Looper.loop(Looper.java:207)
        at android.app.ActivityThread.main(ActivityThread.java:7470)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:958)
```
I assume this is due to the view not existing when the response is returned.

**Comment by TomG736** [comment]
fixed by 94d22fa6f8e21a976b39421d63aeea7a7d2dedf0
